#include <stdio.h>
#include <stdlib.h>
#include "smooth_stratification.h"

Word repl()
{
    SWRITE("Stratification computed. Please select an option.\n");
    SWRITE("  1. print all polynomials\n");
    SWRITE("  2. print all strata\n");
    SWRITE("  0. exit\n");

    Word I = IREAD();
    FILINE();

    if (ISLIST(I)) {
        return -1;
    }

    return I;
}

int main(int argc, char **argv)
{
    /* Start up SACLIB. read data from stdin, robustly, continuing until read is successful. */
    Word i, r, Ps, V, Ds, S, t = 0;
    Word ac; char **av;
    ARGSACLIB(argc,argv,&ac,&av);
    BEGINSACLIB((Word *)&argc);

    /* Initialise S. */
    S = NIL, i = 0;
    while (i < r) {
        S = COMP(NIL, S);
        ++i;
    }

    while (t != 1) {
        t = read_input(&r, &V, &Ps);
    }

    FILINE();

    Ds = stratify(r, Ps, &S, V);

    /* Basic repl. */
    do {
        t = repl();

        switch (t) {
            case 0:
                SWRITE("Exit. Bye bye!");

                break;
            case 1:
                SWRITE("All polynomials generated by the smooth stratification algorithm:\n");
                write_polynomials(r, Ds, V);

                break;
            case 2:
                SWRITE("List of all strata.\n");
                write_output(r, S, V);

                break;
            default:
                SWRITE("Unknown option.\n");

                break;
        }

        SWRITE("\n");
    } while (t != 0); // 0: exit

    /* tidy up */
    ENDSACLIB(SAC_FREEMEM);
    // free(S); /* strata array */
    free(av); /* saclib arguments */

    return 0;
}

